// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: internal/proto/teamx.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TeamX_Register_FullMethodName     = "/teamx.proto.TeamX/Register"
	TeamX_Channel_FullMethodName      = "/teamx.proto.TeamX/Channel"
	TeamX_TransferFile_FullMethodName = "/teamx.proto.TeamX/TransferFile"
)

// TeamXClient is the client API for TeamX service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TeamXClient interface {
	// Register performs a one-shot handshake: client → server.
	// The server returns a unique client_id the client must use thereafter.
	Register(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error)
	// Channel is the main bidirectional communication pipe.
	// Once registered, the client opens this stream and keeps it alive.
	//
	//	Client → Server : Heartbeat / ReportRequest / CommandResult
	//	Server → Client : HeartbeatAck  / Command
	Channel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error)
	// TransferFile handles file upload / download with chunked framing.
	// Phase 7 才启用，Phase 0.2 先定义协议。
	TransferFile(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FileChunk, FileChunk], error)
}

type teamXClient struct {
	cc grpc.ClientConnInterface
}

func NewTeamXClient(cc grpc.ClientConnInterface) TeamXClient {
	return &teamXClient{cc}
}

func (c *teamXClient) Register(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, TeamX_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamXClient) Channel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TeamX_ServiceDesc.Streams[0], TeamX_Channel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TeamX_ChannelClient = grpc.BidiStreamingClient[ClientMessage, ServerMessage]

func (c *teamXClient) TransferFile(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FileChunk, FileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TeamX_ServiceDesc.Streams[1], TeamX_TransferFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileChunk, FileChunk]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TeamX_TransferFileClient = grpc.BidiStreamingClient[FileChunk, FileChunk]

// TeamXServer is the server API for TeamX service.
// All implementations must embed UnimplementedTeamXServer
// for forward compatibility.
type TeamXServer interface {
	// Register performs a one-shot handshake: client → server.
	// The server returns a unique client_id the client must use thereafter.
	Register(context.Context, *HandshakeRequest) (*HandshakeResponse, error)
	// Channel is the main bidirectional communication pipe.
	// Once registered, the client opens this stream and keeps it alive.
	//
	//	Client → Server : Heartbeat / ReportRequest / CommandResult
	//	Server → Client : HeartbeatAck  / Command
	Channel(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error
	// TransferFile handles file upload / download with chunked framing.
	// Phase 7 才启用，Phase 0.2 先定义协议。
	TransferFile(grpc.BidiStreamingServer[FileChunk, FileChunk]) error
	mustEmbedUnimplementedTeamXServer()
}

// UnimplementedTeamXServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTeamXServer struct{}

func (UnimplementedTeamXServer) Register(context.Context, *HandshakeRequest) (*HandshakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedTeamXServer) Channel(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error {
	return status.Error(codes.Unimplemented, "method Channel not implemented")
}
func (UnimplementedTeamXServer) TransferFile(grpc.BidiStreamingServer[FileChunk, FileChunk]) error {
	return status.Error(codes.Unimplemented, "method TransferFile not implemented")
}
func (UnimplementedTeamXServer) mustEmbedUnimplementedTeamXServer() {}
func (UnimplementedTeamXServer) testEmbeddedByValue()               {}

// UnsafeTeamXServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TeamXServer will
// result in compilation errors.
type UnsafeTeamXServer interface {
	mustEmbedUnimplementedTeamXServer()
}

func RegisterTeamXServer(s grpc.ServiceRegistrar, srv TeamXServer) {
	// If the following call panics, it indicates UnimplementedTeamXServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TeamX_ServiceDesc, srv)
}

func _TeamX_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamXServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeamX_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamXServer).Register(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamX_Channel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TeamXServer).Channel(&grpc.GenericServerStream[ClientMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TeamX_ChannelServer = grpc.BidiStreamingServer[ClientMessage, ServerMessage]

func _TeamX_TransferFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TeamXServer).TransferFile(&grpc.GenericServerStream[FileChunk, FileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TeamX_TransferFileServer = grpc.BidiStreamingServer[FileChunk, FileChunk]

// TeamX_ServiceDesc is the grpc.ServiceDesc for TeamX service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TeamX_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "teamx.proto.TeamX",
	HandlerType: (*TeamXServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _TeamX_Register_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Channel",
			Handler:       _TeamX_Channel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "TransferFile",
			Handler:       _TeamX_TransferFile_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/proto/teamx.proto",
}
