// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: teamx.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TeamX_Register_FullMethodName           = "/teamx.proto.TeamX/Register"
	TeamX_Channel_FullMethodName            = "/teamx.proto.TeamX/Channel"
	TeamX_TransferFile_FullMethodName       = "/teamx.proto.TeamX/TransferFile"
	TeamX_ListTerminals_FullMethodName      = "/teamx.proto.TeamX/ListTerminals"
	TeamX_GetTerminal_FullMethodName        = "/teamx.proto.TeamX/GetTerminal"
	TeamX_GetTerminalHistory_FullMethodName = "/teamx.proto.TeamX/GetTerminalHistory"
	TeamX_DisconnectTerminal_FullMethodName = "/teamx.proto.TeamX/DisconnectTerminal"
	TeamX_BlockTerminal_FullMethodName      = "/teamx.proto.TeamX/BlockTerminal"
	TeamX_UnblockTerminal_FullMethodName    = "/teamx.proto.TeamX/UnblockTerminal"
)

// TeamXClient is the client API for TeamX service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TeamXClient interface {
	// Register performs a one-shot handshake: client → server.
	// The server returns a unique client_id the client must use thereafter.
	Register(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error)
	// Channel is the main bidirectional communication pipe.
	// Once registered, the client opens this stream and keeps it alive.
	//
	//	Client → Server : Heartbeat / ReportRequest / CommandResult
	//	Server → Client : HeartbeatAck  / Command
	Channel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error)
	// TransferFile handles file upload / download with chunked framing.
	// Phase 7 才启用，Phase 0.2 先定义协议。
	TransferFile(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FileChunk, FileChunk], error)
	ListTerminals(ctx context.Context, in *ListTerminalsRequest, opts ...grpc.CallOption) (*ListTerminalsResponse, error)
	GetTerminal(ctx context.Context, in *GetTerminalRequest, opts ...grpc.CallOption) (*GetTerminalResponse, error)
	GetTerminalHistory(ctx context.Context, in *GetTerminalHistoryRequest, opts ...grpc.CallOption) (*GetTerminalHistoryResponse, error)
	DisconnectTerminal(ctx context.Context, in *DisconnectTerminalRequest, opts ...grpc.CallOption) (*DisconnectTerminalResponse, error)
	BlockTerminal(ctx context.Context, in *BlockTerminalRequest, opts ...grpc.CallOption) (*BlockTerminalResponse, error)
	UnblockTerminal(ctx context.Context, in *UnblockTerminalRequest, opts ...grpc.CallOption) (*UnblockTerminalResponse, error)
}

type teamXClient struct {
	cc grpc.ClientConnInterface
}

func NewTeamXClient(cc grpc.ClientConnInterface) TeamXClient {
	return &teamXClient{cc}
}

func (c *teamXClient) Register(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, TeamX_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamXClient) Channel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TeamX_ServiceDesc.Streams[0], TeamX_Channel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TeamX_ChannelClient = grpc.BidiStreamingClient[ClientMessage, ServerMessage]

func (c *teamXClient) TransferFile(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FileChunk, FileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TeamX_ServiceDesc.Streams[1], TeamX_TransferFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileChunk, FileChunk]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TeamX_TransferFileClient = grpc.BidiStreamingClient[FileChunk, FileChunk]

func (c *teamXClient) ListTerminals(ctx context.Context, in *ListTerminalsRequest, opts ...grpc.CallOption) (*ListTerminalsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTerminalsResponse)
	err := c.cc.Invoke(ctx, TeamX_ListTerminals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamXClient) GetTerminal(ctx context.Context, in *GetTerminalRequest, opts ...grpc.CallOption) (*GetTerminalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTerminalResponse)
	err := c.cc.Invoke(ctx, TeamX_GetTerminal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamXClient) GetTerminalHistory(ctx context.Context, in *GetTerminalHistoryRequest, opts ...grpc.CallOption) (*GetTerminalHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTerminalHistoryResponse)
	err := c.cc.Invoke(ctx, TeamX_GetTerminalHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamXClient) DisconnectTerminal(ctx context.Context, in *DisconnectTerminalRequest, opts ...grpc.CallOption) (*DisconnectTerminalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisconnectTerminalResponse)
	err := c.cc.Invoke(ctx, TeamX_DisconnectTerminal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamXClient) BlockTerminal(ctx context.Context, in *BlockTerminalRequest, opts ...grpc.CallOption) (*BlockTerminalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlockTerminalResponse)
	err := c.cc.Invoke(ctx, TeamX_BlockTerminal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamXClient) UnblockTerminal(ctx context.Context, in *UnblockTerminalRequest, opts ...grpc.CallOption) (*UnblockTerminalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnblockTerminalResponse)
	err := c.cc.Invoke(ctx, TeamX_UnblockTerminal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TeamXServer is the server API for TeamX service.
// All implementations must embed UnimplementedTeamXServer
// for forward compatibility.
type TeamXServer interface {
	// Register performs a one-shot handshake: client → server.
	// The server returns a unique client_id the client must use thereafter.
	Register(context.Context, *HandshakeRequest) (*HandshakeResponse, error)
	// Channel is the main bidirectional communication pipe.
	// Once registered, the client opens this stream and keeps it alive.
	//
	//	Client → Server : Heartbeat / ReportRequest / CommandResult
	//	Server → Client : HeartbeatAck  / Command
	Channel(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error
	// TransferFile handles file upload / download with chunked framing.
	// Phase 7 才启用，Phase 0.2 先定义协议。
	TransferFile(grpc.BidiStreamingServer[FileChunk, FileChunk]) error
	ListTerminals(context.Context, *ListTerminalsRequest) (*ListTerminalsResponse, error)
	GetTerminal(context.Context, *GetTerminalRequest) (*GetTerminalResponse, error)
	GetTerminalHistory(context.Context, *GetTerminalHistoryRequest) (*GetTerminalHistoryResponse, error)
	DisconnectTerminal(context.Context, *DisconnectTerminalRequest) (*DisconnectTerminalResponse, error)
	BlockTerminal(context.Context, *BlockTerminalRequest) (*BlockTerminalResponse, error)
	UnblockTerminal(context.Context, *UnblockTerminalRequest) (*UnblockTerminalResponse, error)
	mustEmbedUnimplementedTeamXServer()
}

// UnimplementedTeamXServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTeamXServer struct{}

func (UnimplementedTeamXServer) Register(context.Context, *HandshakeRequest) (*HandshakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedTeamXServer) Channel(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error {
	return status.Error(codes.Unimplemented, "method Channel not implemented")
}
func (UnimplementedTeamXServer) TransferFile(grpc.BidiStreamingServer[FileChunk, FileChunk]) error {
	return status.Error(codes.Unimplemented, "method TransferFile not implemented")
}
func (UnimplementedTeamXServer) ListTerminals(context.Context, *ListTerminalsRequest) (*ListTerminalsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTerminals not implemented")
}
func (UnimplementedTeamXServer) GetTerminal(context.Context, *GetTerminalRequest) (*GetTerminalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTerminal not implemented")
}
func (UnimplementedTeamXServer) GetTerminalHistory(context.Context, *GetTerminalHistoryRequest) (*GetTerminalHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTerminalHistory not implemented")
}
func (UnimplementedTeamXServer) DisconnectTerminal(context.Context, *DisconnectTerminalRequest) (*DisconnectTerminalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisconnectTerminal not implemented")
}
func (UnimplementedTeamXServer) BlockTerminal(context.Context, *BlockTerminalRequest) (*BlockTerminalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BlockTerminal not implemented")
}
func (UnimplementedTeamXServer) UnblockTerminal(context.Context, *UnblockTerminalRequest) (*UnblockTerminalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnblockTerminal not implemented")
}
func (UnimplementedTeamXServer) mustEmbedUnimplementedTeamXServer() {}
func (UnimplementedTeamXServer) testEmbeddedByValue()               {}

// UnsafeTeamXServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TeamXServer will
// result in compilation errors.
type UnsafeTeamXServer interface {
	mustEmbedUnimplementedTeamXServer()
}

func RegisterTeamXServer(s grpc.ServiceRegistrar, srv TeamXServer) {
	// If the following call panics, it indicates UnimplementedTeamXServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TeamX_ServiceDesc, srv)
}

func _TeamX_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamXServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeamX_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamXServer).Register(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamX_Channel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TeamXServer).Channel(&grpc.GenericServerStream[ClientMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TeamX_ChannelServer = grpc.BidiStreamingServer[ClientMessage, ServerMessage]

func _TeamX_TransferFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TeamXServer).TransferFile(&grpc.GenericServerStream[FileChunk, FileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TeamX_TransferFileServer = grpc.BidiStreamingServer[FileChunk, FileChunk]

func _TeamX_ListTerminals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTerminalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamXServer).ListTerminals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeamX_ListTerminals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamXServer).ListTerminals(ctx, req.(*ListTerminalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamX_GetTerminal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTerminalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamXServer).GetTerminal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeamX_GetTerminal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamXServer).GetTerminal(ctx, req.(*GetTerminalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamX_GetTerminalHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTerminalHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamXServer).GetTerminalHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeamX_GetTerminalHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamXServer).GetTerminalHistory(ctx, req.(*GetTerminalHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamX_DisconnectTerminal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectTerminalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamXServer).DisconnectTerminal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeamX_DisconnectTerminal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamXServer).DisconnectTerminal(ctx, req.(*DisconnectTerminalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamX_BlockTerminal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockTerminalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamXServer).BlockTerminal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeamX_BlockTerminal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamXServer).BlockTerminal(ctx, req.(*BlockTerminalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamX_UnblockTerminal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnblockTerminalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamXServer).UnblockTerminal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeamX_UnblockTerminal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamXServer).UnblockTerminal(ctx, req.(*UnblockTerminalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TeamX_ServiceDesc is the grpc.ServiceDesc for TeamX service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TeamX_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "teamx.proto.TeamX",
	HandlerType: (*TeamXServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _TeamX_Register_Handler,
		},
		{
			MethodName: "ListTerminals",
			Handler:    _TeamX_ListTerminals_Handler,
		},
		{
			MethodName: "GetTerminal",
			Handler:    _TeamX_GetTerminal_Handler,
		},
		{
			MethodName: "GetTerminalHistory",
			Handler:    _TeamX_GetTerminalHistory_Handler,
		},
		{
			MethodName: "DisconnectTerminal",
			Handler:    _TeamX_DisconnectTerminal_Handler,
		},
		{
			MethodName: "BlockTerminal",
			Handler:    _TeamX_BlockTerminal_Handler,
		},
		{
			MethodName: "UnblockTerminal",
			Handler:    _TeamX_UnblockTerminal_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Channel",
			Handler:       _TeamX_Channel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "TransferFile",
			Handler:       _TeamX_TransferFile_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "teamx.proto",
}
