// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: internal/proto/teamx.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HandshakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`                                // 主机名
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`                                            // 操作系统: linux / windows / darwin
	OsVersion     string                 `protobuf:"bytes,3,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`             // 操作系统版本
	KernelVersion string                 `protobuf:"bytes,4,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"` // 内核版本
	ClientVersion string                 `protobuf:"bytes,5,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"` // TeamX client 版本号
	MacAddrs      []string               `protobuf:"bytes,6,rep,name=mac_addrs,json=macAddrs,proto3" json:"mac_addrs,omitempty"`                // MAC 地址列表（硬件指纹）
	IpAddrs       []string               `protobuf:"bytes,7,rep,name=ip_addrs,json=ipAddrs,proto3" json:"ip_addrs,omitempty"`                   // IP 地址列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_internal_proto_teamx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_teamx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_teamx_proto_rawDescGZIP(), []int{0}
}

func (x *HandshakeRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HandshakeRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *HandshakeRequest) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *HandshakeRequest) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *HandshakeRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *HandshakeRequest) GetMacAddrs() []string {
	if x != nil {
		return x.MacAddrs
	}
	return nil
}

func (x *HandshakeRequest) GetIpAddrs() []string {
	if x != nil {
		return x.IpAddrs
	}
	return nil
}

type HandshakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`                                  // true = 注册成功; false = 被拒绝（黑名单）
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`       // server 分配的唯一 ID (UUID v4)
	ServerTime    string                 `protobuf:"bytes,3,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"` // 服务器当前时间 (RFC 3339), 用于客户端校时
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                         // 拒绝原因或欢迎信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_internal_proto_teamx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_teamx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_teamx_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HandshakeResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *HandshakeResponse) GetServerTime() string {
	if x != nil {
		return x.ServerTime
	}
	return ""
}

func (x *HandshakeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Seq   uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"` // 单调递增序号, 服务端用于去重和乱序检测
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientMessage_Heartbeat
	//	*ClientMessage_ReportRequest
	//	*ClientMessage_CommandResult
	Payload       isClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_internal_proto_teamx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_teamx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_teamx_proto_rawDescGZIP(), []int{2}
}

func (x *ClientMessage) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ClientMessage) GetPayload() isClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ClientMessage) GetReportRequest() *ReportRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_ReportRequest); ok {
			return x.ReportRequest
		}
	}
	return nil
}

func (x *ClientMessage) GetCommandResult() *CommandResult {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_CommandResult); ok {
			return x.CommandResult
		}
	}
	return nil
}

type isClientMessage_Payload interface {
	isClientMessage_Payload()
}

type ClientMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type ClientMessage_ReportRequest struct {
	ReportRequest *ReportRequest `protobuf:"bytes,3,opt,name=report_request,json=reportRequest,proto3,oneof"`
}

type ClientMessage_CommandResult struct {
	CommandResult *CommandResult `protobuf:"bytes,4,opt,name=command_result,json=commandResult,proto3,oneof"`
}

func (*ClientMessage_Heartbeat) isClientMessage_Payload() {}

func (*ClientMessage_ReportRequest) isClientMessage_Payload() {}

func (*ClientMessage_CommandResult) isClientMessage_Payload() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Seq   uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"` // 单调递增序号
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_HeartbeatAck
	//	*ServerMessage_Command
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_internal_proto_teamx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_teamx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_teamx_proto_rawDescGZIP(), []int{3}
}

func (x *ServerMessage) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetHeartbeatAck() *HeartbeatAck {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

func (x *ServerMessage) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Command); ok {
			return x.Command
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_HeartbeatAck struct {
	HeartbeatAck *HeartbeatAck `protobuf:"bytes,2,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

type ServerMessage_Command struct {
	Command *Command `protobuf:"bytes,3,opt,name=command,proto3,oneof"`
}

func (*ServerMessage_HeartbeatAck) isServerMessage_Payload() {}

func (*ServerMessage_Command) isServerMessage_Payload() {}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampUnix int64                  `protobuf:"varint,1,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"` // 客户端发送时间戳 (unix seconds)
	CpuPercent    float32                `protobuf:"fixed32,2,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`         // CPU 使用率 (%)  — 轻量健康指标
	MemPercent    float32                `protobuf:"fixed32,3,opt,name=mem_percent,json=memPercent,proto3" json:"mem_percent,omitempty"`         // 内存使用率 (%)   — 轻量健康指标
	Goroutines    int32                  `protobuf:"varint,4,opt,name=goroutines,proto3" json:"goroutines,omitempty"`                            // client 自身 goroutine 数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_internal_proto_teamx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_teamx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_internal_proto_teamx_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *Heartbeat) GetCpuPercent() float32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *Heartbeat) GetMemPercent() float32 {
	if x != nil {
		return x.MemPercent
	}
	return 0
}

func (x *Heartbeat) GetGoroutines() int32 {
	if x != nil {
		return x.Goroutines
	}
	return 0
}

type HeartbeatAck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServerTimeUnix int64                  `protobuf:"varint,1,opt,name=server_time_unix,json=serverTimeUnix,proto3" json:"server_time_unix,omitempty"` // 服务器收到时间戳
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_internal_proto_teamx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_teamx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_internal_proto_teamx_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatAck) GetServerTimeUnix() int64 {
	if x != nil {
		return x.ServerTimeUnix
	}
	return 0
}

type ReportRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ReportId string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"` // 唯一上报 ID (UUID v4), 用于去重
	// Types that are valid to be assigned to Type:
	//
	//	*ReportRequest_Hardware
	//	*ReportRequest_Software
	//	*ReportRequest_User
	//	*ReportRequest_Process
	//	*ReportRequest_Peripheral
	Type          isReportRequest_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportRequest) Reset() {
	*x = ReportRequest{}
	mi := &file_internal_proto_teamx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRequest) ProtoMessage() {}

func (x *ReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_teamx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRequest.ProtoReflect.Descriptor instead.
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_teamx_proto_rawDescGZIP(), []int{6}
}

func (x *ReportRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *ReportRequest) GetType() isReportRequest_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *ReportRequest) GetHardware() *HardwareInfo {
	if x != nil {
		if x, ok := x.Type.(*ReportRequest_Hardware); ok {
			return x.Hardware
		}
	}
	return nil
}

func (x *ReportRequest) GetSoftware() *SoftwareInfo {
	if x != nil {
		if x, ok := x.Type.(*ReportRequest_Software); ok {
			return x.Software
		}
	}
	return nil
}

func (x *ReportRequest) GetUser() *UserInfo {
	if x != nil {
		if x, ok := x.Type.(*ReportRequest_User); ok {
			return x.User
		}
	}
	return nil
}

func (x *ReportRequest) GetProcess() *ProcessInfo {
	if x != nil {
		if x, ok := x.Type.(*ReportRequest_Process); ok {
			return x.Process
		}
	}
	return nil
}

func (x *ReportRequest) GetPeripheral() *PeripheralInfo {
	if x != nil {
		if x, ok := x.Type.(*ReportRequest_Peripheral); ok {
			return x.Peripheral
		}
	}
	return nil
}

type isReportRequest_Type interface {
	isReportRequest_Type()
}

type ReportRequest_Hardware struct {
	Hardware *HardwareInfo `protobuf:"bytes,10,opt,name=hardware,proto3,oneof"`
}

type ReportRequest_Software struct {
	Software *SoftwareInfo `protobuf:"bytes,11,opt,name=software,proto3,oneof"`
}

type ReportRequest_User struct {
	User *UserInfo `protobuf:"bytes,12,opt,name=user,proto3,oneof"`
}

type ReportRequest_Process struct {
	Process *ProcessInfo `protobuf:"bytes,13,opt,name=process,proto3,oneof"`
}

type ReportRequest_Peripheral struct {
	Peripheral *PeripheralInfo `protobuf:"bytes,14,opt,name=peripheral,proto3,oneof"`
}

func (*ReportRequest_Hardware) isReportRequest_Type() {}

func (*ReportRequest_Software) isReportRequest_Type() {}

func (*ReportRequest_User) isReportRequest_Type() {}

func (*ReportRequest_Process) isReportRequest_Type() {}

func (*ReportRequest_Peripheral) isReportRequest_Type() {}

type HardwareInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           *CPUInfo               `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        *MemoryInfo            `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Disks         []*DiskInfo            `protobuf:"bytes,3,rep,name=disks,proto3" json:"disks,omitempty"`
	Nets          []*NetInfo             `protobuf:"bytes,4,rep,name=nets,proto3" json:"nets,omitempty"`
	Bios          *BIOSInfo              `protobuf:"bytes,5,opt,name=bios,proto3" json:"bios,omitempty"`               // optional
	Motherboard   *MotherboardInfo       `protobuf:"bytes,6,opt,name=motherboard,proto3" json:"motherboard,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HardwareInfo) Reset() {
	*x = HardwareInfo{}
	mi := &file_internal_proto_teamx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardwareInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareInfo) ProtoMessage() {}

func (x *HardwareInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_teamx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareInfo.ProtoReflect.Descriptor instead.
func (*HardwareInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_teamx_proto_rawDescGZIP(), []int{7}
}

func (x *HardwareInfo) GetCpu() *CPUInfo {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *HardwareInfo) GetMemory() *MemoryInfo {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *HardwareInfo) GetDisks() []*DiskInfo {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *HardwareInfo) GetNets() []*NetInfo {
	if x != nil {
		return x.Nets
	}
	return nil
}

func (x *HardwareInfo) GetBios() *BIOSInfo {
	if x != nil {
		return x.Bios
	}
	return nil
}

func (x *HardwareInfo) GetMotherboard() *MotherboardInfo {
	if x != nil {
		return x.Motherboard
	}
	return nil
}

type CPUInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`               // e.g. "Intel Core i7-12700H"
	Cores         int32                  `protobuf:"varint,2,opt,name=cores,proto3" json:"cores,omitempty"`              // 物理核心数
	Threads       int32                  `protobuf:"varint,3,opt,name=threads,proto3" json:"threads,omitempty"`          // 逻辑线程数
	Architecture  string                 `protobuf:"bytes,4,opt,name=architecture,proto3" json:"architecture,omitempty"` // amd64 / arm64
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPUInfo) Reset() {
	*x = CPUInfo{}
	mi := &file_internal_proto_teamx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPUInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUInfo) ProtoMessage() {}

func (x *CPUInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_teamx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUInfo.ProtoReflect.Descriptor instead.
func (*CPUInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_teamx_proto_rawDescGZIP(), []int{8}
}

func (x *CPUInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CPUInfo) GetCores() int32 {
	if x != nil {
		return x.Cores
	}
	return 0
}

func (x *CPUInfo) GetThreads() int32 {
	if x != nil {
		return x.Threads
	}
	return 0
}

func (x *CPUInfo) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

type MemoryInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalBytes     uint64                 `protobuf:"varint,1,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	AvailableBytes uint64                 `protobuf:"varint,2,opt,name=available_bytes,json=availableBytes,proto3" json:"available_bytes,omitempty"`
	UsedBytes      uint64                 `protobuf:"varint,3,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MemoryInfo) Reset() {
	*x = MemoryInfo{}
	mi := &file_internal_proto_teamx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryInfo) ProtoMessage() {}

func (x *MemoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_teamx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryInfo.ProtoReflect.Descriptor instead.
func (*MemoryInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_teamx_proto_rawDescGZIP(), []int{9}
}

func (x *MemoryInfo) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *MemoryInfo) GetAvailableBytes() uint64 {
	if x != nil {
		return x.AvailableBytes
	}
	return 0
}

func (x *MemoryInfo) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

type DiskInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"` // e.g. "C:", "/dev/sda1"
	MountPoint    string                 `protobuf:"bytes,2,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	FsType        string                 `protobuf:"bytes,3,opt,name=fs_type,json=fsType,proto3" json:"fs_type,omitempty"` // NTFS / ext4 / APFS
	TotalBytes    uint64                 `protobuf:"varint,4,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	UsedBytes     uint64                 `protobuf:"varint,5,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	FreeBytes     uint64                 `protobuf:"varint,6,opt,name=free_bytes,json=freeBytes,proto3" json:"free_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskInfo) Reset() {
	*x = DiskInfo{}
	mi := &file_internal_proto_teamx_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskInfo) ProtoMessage() {}

func (x *DiskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_teamx_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskInfo.ProtoReflect.Descriptor instead.
func (*DiskInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_teamx_proto_rawDescGZIP(), []int{10}
}

func (x *DiskInfo) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *DiskInfo) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *DiskInfo) GetFsType() string {
	if x != nil {
		return x.FsType
	}
	return ""
}

func (x *DiskInfo) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *DiskInfo) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *DiskInfo) GetFreeBytes() uint64 {
	if x != nil {
		return x.FreeBytes
	}
	return 0
}

type NetInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // e.g. "eth0", "WLAN"
	MacAddr       string                 `protobuf:"bytes,2,opt,name=mac_addr,json=macAddr,proto3" json:"mac_addr,omitempty"`
	IpAddrs       []string               `protobuf:"bytes,3,rep,name=ip_addrs,json=ipAddrs,proto3" json:"ip_addrs,omitempty"`
	IsLoopback    bool                   `protobuf:"varint,4,opt,name=is_loopback,json=isLoopback,proto3" json:"is_loopback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetInfo) Reset() {
	*x = NetInfo{}
	mi := &file_internal_proto_teamx_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetInfo) ProtoMessage() {}

func (x *NetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_teamx_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetInfo.ProtoReflect.Descriptor instead.
func (*NetInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_teamx_proto_rawDescGZIP(), []int{11}
}

func (x *NetInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetInfo) GetMacAddr() string {
	if x != nil {
		return x.MacAddr
	}
	return ""
}

func (x *NetInfo) GetIpAddrs() []string {
	if x != nil {
		return x.IpAddrs
	}
	return nil
}

func (x *NetInfo) GetIsLoopback() bool {
	if x != nil {
		return x.IsLoopback
	}
	return false
}

type BIOSInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vendor        string                 `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	ReleaseDate   string                 `protobuf:"bytes,3,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BIOSInfo) Reset() {
	*x = BIOSInfo{}
	mi := &file_internal_proto_teamx_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BIOSInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BIOSInfo) ProtoMessage() {}

func (x *BIOSInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_teamx_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BIOSInfo.ProtoReflect.Descriptor instead.
func (*BIOSInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_teamx_proto_rawDescGZIP(), []int{12}
}

func (x *BIOSInfo) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *BIOSInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *BIOSInfo) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

type MotherboardInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manufacturer  string                 `protobuf:"bytes,1,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Product       string                 `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	Serial        string                 `protobuf:"bytes,3,opt,name=serial,proto3" json:"serial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MotherboardInfo) Reset() {
	*x = MotherboardInfo{}
	mi := &file_internal_proto_teamx_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MotherboardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MotherboardInfo) ProtoMessage() {}

func (x *MotherboardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_teamx_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MotherboardInfo.ProtoReflect.Descriptor instead.
func (*MotherboardInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_teamx_proto_rawDescGZIP(), []int{13}
}

func (x *MotherboardInfo) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *MotherboardInfo) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *MotherboardInfo) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

type SoftwareInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*SoftwareItem        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // 总数（支持分批上报）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SoftwareInfo) Reset() {
	*x = SoftwareInfo{}
	mi := &file_internal_proto_teamx_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoftwareInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoftwareInfo) ProtoMessage() {}

func (x *SoftwareInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_teamx_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoftwareInfo.ProtoReflect.Descriptor instead.
func (*SoftwareInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_teamx_proto_rawDescGZIP(), []int{14}
}

func (x *SoftwareInfo) GetItems() []*SoftwareItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SoftwareInfo) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type SoftwareItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Publisher     string                 `protobuf:"bytes,3,opt,name=publisher,proto3" json:"publisher,omitempty"` // 发行商
	InstallDate   string                 `protobuf:"bytes,4,opt,name=install_date,json=installDate,proto3" json:"install_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SoftwareItem) Reset() {
	*x = SoftwareItem{}
	mi := &file_internal_proto_teamx_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoftwareItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoftwareItem) ProtoMessage() {}

func (x *SoftwareItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_teamx_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoftwareItem.ProtoReflect.Descriptor instead.
func (*SoftwareItem) Descriptor() ([]byte, []int) {
	return file_internal_proto_teamx_proto_rawDescGZIP(), []int{15}
}

func (x *SoftwareItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SoftwareItem) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SoftwareItem) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *SoftwareItem) GetInstallDate() string {
	if x != nil {
		return x.InstallDate
	}
	return ""
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserAccount         `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	CurrentLogins []string               `protobuf:"bytes,2,rep,name=current_logins,json=currentLogins,proto3" json:"current_logins,omitempty"` // 当前登录用户名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_internal_proto_teamx_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_teamx_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_teamx_proto_rawDescGZIP(), []int{16}
}

func (x *UserInfo) GetUsers() []*UserAccount {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *UserInfo) GetCurrentLogins() []string {
	if x != nil {
		return x.CurrentLogins
	}
	return nil
}

type UserAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`     // user SID (Windows) or uid (Linux)
	Group         string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"` // 主要组
	HomeDir       string                 `protobuf:"bytes,4,opt,name=home_dir,json=homeDir,proto3" json:"home_dir,omitempty"`
	Shell         string                 `protobuf:"bytes,5,opt,name=shell,proto3" json:"shell,omitempty"` // 默认 shell
	IsAdmin       bool                   `protobuf:"varint,6,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	IsDisabled    bool                   `protobuf:"varint,7,opt,name=is_disabled,json=isDisabled,proto3" json:"is_disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAccount) Reset() {
	*x = UserAccount{}
	mi := &file_internal_proto_teamx_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAccount) ProtoMessage() {}

func (x *UserAccount) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_teamx_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAccount.ProtoReflect.Descriptor instead.
func (*UserAccount) Descriptor() ([]byte, []int) {
	return file_internal_proto_teamx_proto_rawDescGZIP(), []int{17}
}

func (x *UserAccount) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserAccount) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *UserAccount) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *UserAccount) GetHomeDir() string {
	if x != nil {
		return x.HomeDir
	}
	return ""
}

func (x *UserAccount) GetShell() string {
	if x != nil {
		return x.Shell
	}
	return ""
}

func (x *UserAccount) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *UserAccount) GetIsDisabled() bool {
	if x != nil {
		return x.IsDisabled
	}
	return false
}

type ProcessInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ProcessItem         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_internal_proto_teamx_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_teamx_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_teamx_proto_rawDescGZIP(), []int{18}
}

func (x *ProcessInfo) GetItems() []*ProcessItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ProcessInfo) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type ProcessItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Ppid          int32                  `protobuf:"varint,2,opt,name=ppid,proto3" json:"ppid,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	User          string                 `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	CpuPercent    float32                `protobuf:"fixed32,5,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemBytes      uint64                 `protobuf:"varint,6,opt,name=mem_bytes,json=memBytes,proto3" json:"mem_bytes,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`   // running / sleeping / stopped / zombie
	Cmdline       string                 `protobuf:"bytes,8,opt,name=cmdline,proto3" json:"cmdline,omitempty"` // 完整命令行
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessItem) Reset() {
	*x = ProcessItem{}
	mi := &file_internal_proto_teamx_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessItem) ProtoMessage() {}

func (x *ProcessItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_teamx_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessItem.ProtoReflect.Descriptor instead.
func (*ProcessItem) Descriptor() ([]byte, []int) {
	return file_internal_proto_teamx_proto_rawDescGZIP(), []int{19}
}

func (x *ProcessItem) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessItem) GetPpid() int32 {
	if x != nil {
		return x.Ppid
	}
	return 0
}

func (x *ProcessItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessItem) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ProcessItem) GetCpuPercent() float32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ProcessItem) GetMemBytes() uint64 {
	if x != nil {
		return x.MemBytes
	}
	return 0
}

func (x *ProcessItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProcessItem) GetCmdline() string {
	if x != nil {
		return x.Cmdline
	}
	return ""
}

type PeripheralInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsbDevices    []*USBDevice           `protobuf:"bytes,1,rep,name=usb_devices,json=usbDevices,proto3" json:"usb_devices,omitempty"`
	Printers      []*Printer             `protobuf:"bytes,2,rep,name=printers,proto3" json:"printers,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeripheralInfo) Reset() {
	*x = PeripheralInfo{}
	mi := &file_internal_proto_teamx_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeripheralInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeripheralInfo) ProtoMessage() {}

func (x *PeripheralInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_teamx_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeripheralInfo.ProtoReflect.Descriptor instead.
func (*PeripheralInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_teamx_proto_rawDescGZIP(), []int{20}
}

func (x *PeripheralInfo) GetUsbDevices() []*USBDevice {
	if x != nil {
		return x.UsbDevices
	}
	return nil
}

func (x *PeripheralInfo) GetPrinters() []*Printer {
	if x != nil {
		return x.Printers
	}
	return nil
}

type USBDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	VendorId      string                 `protobuf:"bytes,2,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Serial        string                 `protobuf:"bytes,4,opt,name=serial,proto3" json:"serial,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *USBDevice) Reset() {
	*x = USBDevice{}
	mi := &file_internal_proto_teamx_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *USBDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*USBDevice) ProtoMessage() {}

func (x *USBDevice) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_teamx_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use USBDevice.ProtoReflect.Descriptor instead.
func (*USBDevice) Descriptor() ([]byte, []int) {
	return file_internal_proto_teamx_proto_rawDescGZIP(), []int{21}
}

func (x *USBDevice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *USBDevice) GetVendorId() string {
	if x != nil {
		return x.VendorId
	}
	return ""
}

func (x *USBDevice) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *USBDevice) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

type Printer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Driver        string                 `protobuf:"bytes,2,opt,name=driver,proto3" json:"driver,omitempty"`
	Port          string                 `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	IsDefault     bool                   `protobuf:"varint,4,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Printer) Reset() {
	*x = Printer{}
	mi := &file_internal_proto_teamx_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Printer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Printer) ProtoMessage() {}

func (x *Printer) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_teamx_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Printer.ProtoReflect.Descriptor instead.
func (*Printer) Descriptor() ([]byte, []int) {
	return file_internal_proto_teamx_proto_rawDescGZIP(), []int{22}
}

func (x *Printer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Printer) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *Printer) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *Printer) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`                                                    // 唯一命令 ID (UUID v4)
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                                                                               // 命令类型枚举: CollectNow | RunScript | KillProcess | UpdateConfig | Upgrade | Restart | Shutdown
	Params        map[string]string      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 灵活参数，不同命令类型自由组合
	TimeoutSec    int64                  `protobuf:"varint,4,opt,name=timeout_sec,json=timeoutSec,proto3" json:"timeout_sec,omitempty"`                                                // 超时时间 (秒), 0 = 无超时
	CreatedAtUnix int64                  `protobuf:"varint,5,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`                                     // 命令创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_internal_proto_teamx_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_teamx_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_internal_proto_teamx_proto_rawDescGZIP(), []int{23}
}

func (x *Command) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *Command) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Command) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Command) GetTimeoutSec() int64 {
	if x != nil {
		return x.TimeoutSec
	}
	return 0
}

func (x *Command) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

type CommandResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CommandId      string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // Executing | Completed | Failed | Timeout
	ExitCode       int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout         string                 `protobuf:"bytes,4,opt,name=stdout,proto3" json:"stdout,omitempty"` // 标准输出
	Stderr         string                 `protobuf:"bytes,5,opt,name=stderr,proto3" json:"stderr,omitempty"` // 标准错误
	StartedAtUnix  int64                  `protobuf:"varint,6,opt,name=started_at_unix,json=startedAtUnix,proto3" json:"started_at_unix,omitempty"`
	FinishedAtUnix int64                  `protobuf:"varint,7,opt,name=finished_at_unix,json=finishedAtUnix,proto3" json:"finished_at_unix,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 失败原因（如有）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_internal_proto_teamx_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_teamx_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_internal_proto_teamx_proto_rawDescGZIP(), []int{24}
}

func (x *CommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CommandResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandResult) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *CommandResult) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *CommandResult) GetStartedAtUnix() int64 {
	if x != nil {
		return x.StartedAtUnix
	}
	return 0
}

func (x *CommandResult) GetFinishedAtUnix() int64 {
	if x != nil {
		return x.FinishedAtUnix
	}
	return 0
}

func (x *CommandResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type FileChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Seq   uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*FileChunk_TransferRequest
	//	*FileChunk_TransferResponse
	//	*FileChunk_FileData
	Payload       isFileChunk_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_internal_proto_teamx_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_teamx_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_internal_proto_teamx_proto_rawDescGZIP(), []int{25}
}

func (x *FileChunk) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *FileChunk) GetPayload() isFileChunk_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *FileChunk) GetTransferRequest() *FileTransferRequest {
	if x != nil {
		if x, ok := x.Payload.(*FileChunk_TransferRequest); ok {
			return x.TransferRequest
		}
	}
	return nil
}

func (x *FileChunk) GetTransferResponse() *FileTransferResponse {
	if x != nil {
		if x, ok := x.Payload.(*FileChunk_TransferResponse); ok {
			return x.TransferResponse
		}
	}
	return nil
}

func (x *FileChunk) GetFileData() *FileData {
	if x != nil {
		if x, ok := x.Payload.(*FileChunk_FileData); ok {
			return x.FileData
		}
	}
	return nil
}

type isFileChunk_Payload interface {
	isFileChunk_Payload()
}

type FileChunk_TransferRequest struct {
	TransferRequest *FileTransferRequest `protobuf:"bytes,2,opt,name=transfer_request,json=transferRequest,proto3,oneof"`
}

type FileChunk_TransferResponse struct {
	TransferResponse *FileTransferResponse `protobuf:"bytes,3,opt,name=transfer_response,json=transferResponse,proto3,oneof"`
}

type FileChunk_FileData struct {
	FileData *FileData `protobuf:"bytes,4,opt,name=file_data,json=fileData,proto3,oneof"`
}

func (*FileChunk_TransferRequest) isFileChunk_Payload() {}

func (*FileChunk_TransferResponse) isFileChunk_Payload() {}

func (*FileChunk_FileData) isFileChunk_Payload() {}

type FileTransferRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 第一帧：描述传输意图
	TransferId    string `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"` // 唯一传输 ID
	Path          string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`                               // 远程文件路径
	SizeBytes     int64  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`   // 文件大小 (upload 时必填; download 时 server 返回)
	Direction     string `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"`                     // "upload" or "download"
	ChunkSize     int32  `protobuf:"varint,5,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`   // 协商分片大小, 默认 65536 (64 KiB)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileTransferRequest) Reset() {
	*x = FileTransferRequest{}
	mi := &file_internal_proto_teamx_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTransferRequest) ProtoMessage() {}

func (x *FileTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_teamx_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTransferRequest.ProtoReflect.Descriptor instead.
func (*FileTransferRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_teamx_proto_rawDescGZIP(), []int{26}
}

func (x *FileTransferRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *FileTransferRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileTransferRequest) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FileTransferRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *FileTransferRequest) GetChunkSize() int32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

type FileTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`                             // server 是否接受传输
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                                // 拒绝原因
	ResumeOffset  int64                  `protobuf:"varint,4,opt,name=resume_offset,json=resumeOffset,proto3" json:"resume_offset,omitempty"` // 断点续传偏移量 (bytes)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileTransferResponse) Reset() {
	*x = FileTransferResponse{}
	mi := &file_internal_proto_teamx_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTransferResponse) ProtoMessage() {}

func (x *FileTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_teamx_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTransferResponse.ProtoReflect.Descriptor instead.
func (*FileTransferResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_teamx_proto_rawDescGZIP(), []int{27}
}

func (x *FileTransferResponse) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *FileTransferResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *FileTransferResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FileTransferResponse) GetResumeOffset() int64 {
	if x != nil {
		return x.ResumeOffset
	}
	return 0
}

type FileData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`               // 此分片在文件中的偏移量
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`                   // 此分片大小 (最后一个分片可能小于 chunk_size)
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`                    // 分片数据
	IsLast        bool                   `protobuf:"varint,5,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"` // 是否最后一个分片
	Checksum      string                 `protobuf:"bytes,6,opt,name=checksum,proto3" json:"checksum,omitempty"`            // SHA256 of this chunk (optional, for integrity)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileData) Reset() {
	*x = FileData{}
	mi := &file_internal_proto_teamx_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileData) ProtoMessage() {}

func (x *FileData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_teamx_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileData.ProtoReflect.Descriptor instead.
func (*FileData) Descriptor() ([]byte, []int) {
	return file_internal_proto_teamx_proto_rawDescGZIP(), []int{28}
}

func (x *FileData) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *FileData) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FileData) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileData) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

func (x *FileData) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

var File_internal_proto_teamx_proto protoreflect.FileDescriptor

const file_internal_proto_teamx_proto_rawDesc = "" +
	"\n" +
	"\x1ainternal/proto/teamx.proto\x12\vteamx.proto\"\xe3\x01\n" +
	"\x10HandshakeRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x1d\n" +
	"\n" +
	"os_version\x18\x03 \x01(\tR\tosVersion\x12%\n" +
	"\x0ekernel_version\x18\x04 \x01(\tR\rkernelVersion\x12%\n" +
	"\x0eclient_version\x18\x05 \x01(\tR\rclientVersion\x12\x1b\n" +
	"\tmac_addrs\x18\x06 \x03(\tR\bmacAddrs\x12\x19\n" +
	"\bip_addrs\x18\a \x03(\tR\aipAddrs\"{\n" +
	"\x11HandshakeResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x1f\n" +
	"\vserver_time\x18\x03 \x01(\tR\n" +
	"serverTime\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xee\x01\n" +
	"\rClientMessage\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x126\n" +
	"\theartbeat\x18\x02 \x01(\v2\x16.teamx.proto.HeartbeatH\x00R\theartbeat\x12C\n" +
	"\x0ereport_request\x18\x03 \x01(\v2\x1a.teamx.proto.ReportRequestH\x00R\rreportRequest\x12C\n" +
	"\x0ecommand_result\x18\x04 \x01(\v2\x1a.teamx.proto.CommandResultH\x00R\rcommandResultB\t\n" +
	"\apayload\"\xa0\x01\n" +
	"\rServerMessage\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12@\n" +
	"\rheartbeat_ack\x18\x02 \x01(\v2\x19.teamx.proto.HeartbeatAckH\x00R\fheartbeatAck\x120\n" +
	"\acommand\x18\x03 \x01(\v2\x14.teamx.proto.CommandH\x00R\acommandB\t\n" +
	"\apayload\"\x94\x01\n" +
	"\tHeartbeat\x12%\n" +
	"\x0etimestamp_unix\x18\x01 \x01(\x03R\rtimestampUnix\x12\x1f\n" +
	"\vcpu_percent\x18\x02 \x01(\x02R\n" +
	"cpuPercent\x12\x1f\n" +
	"\vmem_percent\x18\x03 \x01(\x02R\n" +
	"memPercent\x12\x1e\n" +
	"\n" +
	"goroutines\x18\x04 \x01(\x05R\n" +
	"goroutines\"8\n" +
	"\fHeartbeatAck\x12(\n" +
	"\x10server_time_unix\x18\x01 \x01(\x03R\x0eserverTimeUnix\"\xc8\x02\n" +
	"\rReportRequest\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x127\n" +
	"\bhardware\x18\n" +
	" \x01(\v2\x19.teamx.proto.HardwareInfoH\x00R\bhardware\x127\n" +
	"\bsoftware\x18\v \x01(\v2\x19.teamx.proto.SoftwareInfoH\x00R\bsoftware\x12+\n" +
	"\x04user\x18\f \x01(\v2\x15.teamx.proto.UserInfoH\x00R\x04user\x124\n" +
	"\aprocess\x18\r \x01(\v2\x18.teamx.proto.ProcessInfoH\x00R\aprocess\x12=\n" +
	"\n" +
	"peripheral\x18\x0e \x01(\v2\x1b.teamx.proto.PeripheralInfoH\x00R\n" +
	"peripheralB\x06\n" +
	"\x04type\"\xa9\x02\n" +
	"\fHardwareInfo\x12&\n" +
	"\x03cpu\x18\x01 \x01(\v2\x14.teamx.proto.CPUInfoR\x03cpu\x12/\n" +
	"\x06memory\x18\x02 \x01(\v2\x17.teamx.proto.MemoryInfoR\x06memory\x12+\n" +
	"\x05disks\x18\x03 \x03(\v2\x15.teamx.proto.DiskInfoR\x05disks\x12(\n" +
	"\x04nets\x18\x04 \x03(\v2\x14.teamx.proto.NetInfoR\x04nets\x12)\n" +
	"\x04bios\x18\x05 \x01(\v2\x15.teamx.proto.BIOSInfoR\x04bios\x12>\n" +
	"\vmotherboard\x18\x06 \x01(\v2\x1c.teamx.proto.MotherboardInfoR\vmotherboard\"s\n" +
	"\aCPUInfo\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x14\n" +
	"\x05cores\x18\x02 \x01(\x05R\x05cores\x12\x18\n" +
	"\athreads\x18\x03 \x01(\x05R\athreads\x12\"\n" +
	"\farchitecture\x18\x04 \x01(\tR\farchitecture\"u\n" +
	"\n" +
	"MemoryInfo\x12\x1f\n" +
	"\vtotal_bytes\x18\x01 \x01(\x04R\n" +
	"totalBytes\x12'\n" +
	"\x0favailable_bytes\x18\x02 \x01(\x04R\x0eavailableBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x03 \x01(\x04R\tusedBytes\"\xbb\x01\n" +
	"\bDiskInfo\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x1f\n" +
	"\vmount_point\x18\x02 \x01(\tR\n" +
	"mountPoint\x12\x17\n" +
	"\afs_type\x18\x03 \x01(\tR\x06fsType\x12\x1f\n" +
	"\vtotal_bytes\x18\x04 \x01(\x04R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x05 \x01(\x04R\tusedBytes\x12\x1d\n" +
	"\n" +
	"free_bytes\x18\x06 \x01(\x04R\tfreeBytes\"t\n" +
	"\aNetInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bmac_addr\x18\x02 \x01(\tR\amacAddr\x12\x19\n" +
	"\bip_addrs\x18\x03 \x03(\tR\aipAddrs\x12\x1f\n" +
	"\vis_loopback\x18\x04 \x01(\bR\n" +
	"isLoopback\"_\n" +
	"\bBIOSInfo\x12\x16\n" +
	"\x06vendor\x18\x01 \x01(\tR\x06vendor\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12!\n" +
	"\frelease_date\x18\x03 \x01(\tR\vreleaseDate\"g\n" +
	"\x0fMotherboardInfo\x12\"\n" +
	"\fmanufacturer\x18\x01 \x01(\tR\fmanufacturer\x12\x18\n" +
	"\aproduct\x18\x02 \x01(\tR\aproduct\x12\x16\n" +
	"\x06serial\x18\x03 \x01(\tR\x06serial\"`\n" +
	"\fSoftwareInfo\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.teamx.proto.SoftwareItemR\x05items\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"}\n" +
	"\fSoftwareItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1c\n" +
	"\tpublisher\x18\x03 \x01(\tR\tpublisher\x12!\n" +
	"\finstall_date\x18\x04 \x01(\tR\vinstallDate\"a\n" +
	"\bUserInfo\x12.\n" +
	"\x05users\x18\x01 \x03(\v2\x18.teamx.proto.UserAccountR\x05users\x12%\n" +
	"\x0ecurrent_logins\x18\x02 \x03(\tR\rcurrentLogins\"\xbe\x01\n" +
	"\vUserAccount\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\x12\x19\n" +
	"\bhome_dir\x18\x04 \x01(\tR\ahomeDir\x12\x14\n" +
	"\x05shell\x18\x05 \x01(\tR\x05shell\x12\x19\n" +
	"\bis_admin\x18\x06 \x01(\bR\aisAdmin\x12\x1f\n" +
	"\vis_disabled\x18\a \x01(\bR\n" +
	"isDisabled\"^\n" +
	"\vProcessInfo\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.teamx.proto.ProcessItemR\x05items\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xcb\x01\n" +
	"\vProcessItem\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04ppid\x18\x02 \x01(\x05R\x04ppid\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04user\x12\x1f\n" +
	"\vcpu_percent\x18\x05 \x01(\x02R\n" +
	"cpuPercent\x12\x1b\n" +
	"\tmem_bytes\x18\x06 \x01(\x04R\bmemBytes\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x18\n" +
	"\acmdline\x18\b \x01(\tR\acmdline\"{\n" +
	"\x0ePeripheralInfo\x127\n" +
	"\vusb_devices\x18\x01 \x03(\v2\x16.teamx.proto.USBDeviceR\n" +
	"usbDevices\x120\n" +
	"\bprinters\x18\x02 \x03(\v2\x14.teamx.proto.PrinterR\bprinters\"s\n" +
	"\tUSBDevice\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tvendor_id\x18\x02 \x01(\tR\bvendorId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\tR\tproductId\x12\x16\n" +
	"\x06serial\x18\x04 \x01(\tR\x06serial\"h\n" +
	"\aPrinter\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06driver\x18\x02 \x01(\tR\x06driver\x12\x12\n" +
	"\x04port\x18\x03 \x01(\tR\x04port\x12\x1d\n" +
	"\n" +
	"is_default\x18\x04 \x01(\bR\tisDefault\"\xfa\x01\n" +
	"\aCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x128\n" +
	"\x06params\x18\x03 \x03(\v2 .teamx.proto.Command.ParamsEntryR\x06params\x12\x1f\n" +
	"\vtimeout_sec\x18\x04 \x01(\x03R\n" +
	"timeoutSec\x12&\n" +
	"\x0fcreated_at_unix\x18\x05 \x01(\x03R\rcreatedAtUnix\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8a\x02\n" +
	"\rCommandResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x04 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x05 \x01(\tR\x06stderr\x12&\n" +
	"\x0fstarted_at_unix\x18\x06 \x01(\x03R\rstartedAtUnix\x12(\n" +
	"\x10finished_at_unix\x18\a \x01(\x03R\x0efinishedAtUnix\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\"\xff\x01\n" +
	"\tFileChunk\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12M\n" +
	"\x10transfer_request\x18\x02 \x01(\v2 .teamx.proto.FileTransferRequestH\x00R\x0ftransferRequest\x12P\n" +
	"\x11transfer_response\x18\x03 \x01(\v2!.teamx.proto.FileTransferResponseH\x00R\x10transferResponse\x124\n" +
	"\tfile_data\x18\x04 \x01(\v2\x15.teamx.proto.FileDataH\x00R\bfileDataB\t\n" +
	"\apayload\"\xa6\x01\n" +
	"\x13FileTransferRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12\x1c\n" +
	"\tdirection\x18\x04 \x01(\tR\tdirection\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x05 \x01(\x05R\tchunkSize\"\x92\x01\n" +
	"\x14FileTransferResponse\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12#\n" +
	"\rresume_offset\x18\x04 \x01(\x03R\fresumeOffset\"\xa0\x01\n" +
	"\bFileData\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x17\n" +
	"\ais_last\x18\x05 \x01(\bR\x06isLast\x12\x1a\n" +
	"\bchecksum\x18\x06 \x01(\tR\bchecksum2\xdd\x01\n" +
	"\x05TeamX\x12I\n" +
	"\bRegister\x12\x1d.teamx.proto.HandshakeRequest\x1a\x1e.teamx.proto.HandshakeResponse\x12E\n" +
	"\aChannel\x12\x1a.teamx.proto.ClientMessage\x1a\x1a.teamx.proto.ServerMessage(\x010\x01\x12B\n" +
	"\fTransferFile\x12\x16.teamx.proto.FileChunk\x1a\x16.teamx.proto.FileChunk(\x010\x01B\x16Z\x14teamx/internal/protob\x06proto3"

var (
	file_internal_proto_teamx_proto_rawDescOnce sync.Once
	file_internal_proto_teamx_proto_rawDescData []byte
)

func file_internal_proto_teamx_proto_rawDescGZIP() []byte {
	file_internal_proto_teamx_proto_rawDescOnce.Do(func() {
		file_internal_proto_teamx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_teamx_proto_rawDesc), len(file_internal_proto_teamx_proto_rawDesc)))
	})
	return file_internal_proto_teamx_proto_rawDescData
}

var file_internal_proto_teamx_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_internal_proto_teamx_proto_goTypes = []any{
	(*HandshakeRequest)(nil),     // 0: teamx.proto.HandshakeRequest
	(*HandshakeResponse)(nil),    // 1: teamx.proto.HandshakeResponse
	(*ClientMessage)(nil),        // 2: teamx.proto.ClientMessage
	(*ServerMessage)(nil),        // 3: teamx.proto.ServerMessage
	(*Heartbeat)(nil),            // 4: teamx.proto.Heartbeat
	(*HeartbeatAck)(nil),         // 5: teamx.proto.HeartbeatAck
	(*ReportRequest)(nil),        // 6: teamx.proto.ReportRequest
	(*HardwareInfo)(nil),         // 7: teamx.proto.HardwareInfo
	(*CPUInfo)(nil),              // 8: teamx.proto.CPUInfo
	(*MemoryInfo)(nil),           // 9: teamx.proto.MemoryInfo
	(*DiskInfo)(nil),             // 10: teamx.proto.DiskInfo
	(*NetInfo)(nil),              // 11: teamx.proto.NetInfo
	(*BIOSInfo)(nil),             // 12: teamx.proto.BIOSInfo
	(*MotherboardInfo)(nil),      // 13: teamx.proto.MotherboardInfo
	(*SoftwareInfo)(nil),         // 14: teamx.proto.SoftwareInfo
	(*SoftwareItem)(nil),         // 15: teamx.proto.SoftwareItem
	(*UserInfo)(nil),             // 16: teamx.proto.UserInfo
	(*UserAccount)(nil),          // 17: teamx.proto.UserAccount
	(*ProcessInfo)(nil),          // 18: teamx.proto.ProcessInfo
	(*ProcessItem)(nil),          // 19: teamx.proto.ProcessItem
	(*PeripheralInfo)(nil),       // 20: teamx.proto.PeripheralInfo
	(*USBDevice)(nil),            // 21: teamx.proto.USBDevice
	(*Printer)(nil),              // 22: teamx.proto.Printer
	(*Command)(nil),              // 23: teamx.proto.Command
	(*CommandResult)(nil),        // 24: teamx.proto.CommandResult
	(*FileChunk)(nil),            // 25: teamx.proto.FileChunk
	(*FileTransferRequest)(nil),  // 26: teamx.proto.FileTransferRequest
	(*FileTransferResponse)(nil), // 27: teamx.proto.FileTransferResponse
	(*FileData)(nil),             // 28: teamx.proto.FileData
	nil,                          // 29: teamx.proto.Command.ParamsEntry
}
var file_internal_proto_teamx_proto_depIdxs = []int32{
	4,  // 0: teamx.proto.ClientMessage.heartbeat:type_name -> teamx.proto.Heartbeat
	6,  // 1: teamx.proto.ClientMessage.report_request:type_name -> teamx.proto.ReportRequest
	24, // 2: teamx.proto.ClientMessage.command_result:type_name -> teamx.proto.CommandResult
	5,  // 3: teamx.proto.ServerMessage.heartbeat_ack:type_name -> teamx.proto.HeartbeatAck
	23, // 4: teamx.proto.ServerMessage.command:type_name -> teamx.proto.Command
	7,  // 5: teamx.proto.ReportRequest.hardware:type_name -> teamx.proto.HardwareInfo
	14, // 6: teamx.proto.ReportRequest.software:type_name -> teamx.proto.SoftwareInfo
	16, // 7: teamx.proto.ReportRequest.user:type_name -> teamx.proto.UserInfo
	18, // 8: teamx.proto.ReportRequest.process:type_name -> teamx.proto.ProcessInfo
	20, // 9: teamx.proto.ReportRequest.peripheral:type_name -> teamx.proto.PeripheralInfo
	8,  // 10: teamx.proto.HardwareInfo.cpu:type_name -> teamx.proto.CPUInfo
	9,  // 11: teamx.proto.HardwareInfo.memory:type_name -> teamx.proto.MemoryInfo
	10, // 12: teamx.proto.HardwareInfo.disks:type_name -> teamx.proto.DiskInfo
	11, // 13: teamx.proto.HardwareInfo.nets:type_name -> teamx.proto.NetInfo
	12, // 14: teamx.proto.HardwareInfo.bios:type_name -> teamx.proto.BIOSInfo
	13, // 15: teamx.proto.HardwareInfo.motherboard:type_name -> teamx.proto.MotherboardInfo
	15, // 16: teamx.proto.SoftwareInfo.items:type_name -> teamx.proto.SoftwareItem
	17, // 17: teamx.proto.UserInfo.users:type_name -> teamx.proto.UserAccount
	19, // 18: teamx.proto.ProcessInfo.items:type_name -> teamx.proto.ProcessItem
	21, // 19: teamx.proto.PeripheralInfo.usb_devices:type_name -> teamx.proto.USBDevice
	22, // 20: teamx.proto.PeripheralInfo.printers:type_name -> teamx.proto.Printer
	29, // 21: teamx.proto.Command.params:type_name -> teamx.proto.Command.ParamsEntry
	26, // 22: teamx.proto.FileChunk.transfer_request:type_name -> teamx.proto.FileTransferRequest
	27, // 23: teamx.proto.FileChunk.transfer_response:type_name -> teamx.proto.FileTransferResponse
	28, // 24: teamx.proto.FileChunk.file_data:type_name -> teamx.proto.FileData
	0,  // 25: teamx.proto.TeamX.Register:input_type -> teamx.proto.HandshakeRequest
	2,  // 26: teamx.proto.TeamX.Channel:input_type -> teamx.proto.ClientMessage
	25, // 27: teamx.proto.TeamX.TransferFile:input_type -> teamx.proto.FileChunk
	1,  // 28: teamx.proto.TeamX.Register:output_type -> teamx.proto.HandshakeResponse
	3,  // 29: teamx.proto.TeamX.Channel:output_type -> teamx.proto.ServerMessage
	25, // 30: teamx.proto.TeamX.TransferFile:output_type -> teamx.proto.FileChunk
	28, // [28:31] is the sub-list for method output_type
	25, // [25:28] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_internal_proto_teamx_proto_init() }
func file_internal_proto_teamx_proto_init() {
	if File_internal_proto_teamx_proto != nil {
		return
	}
	file_internal_proto_teamx_proto_msgTypes[2].OneofWrappers = []any{
		(*ClientMessage_Heartbeat)(nil),
		(*ClientMessage_ReportRequest)(nil),
		(*ClientMessage_CommandResult)(nil),
	}
	file_internal_proto_teamx_proto_msgTypes[3].OneofWrappers = []any{
		(*ServerMessage_HeartbeatAck)(nil),
		(*ServerMessage_Command)(nil),
	}
	file_internal_proto_teamx_proto_msgTypes[6].OneofWrappers = []any{
		(*ReportRequest_Hardware)(nil),
		(*ReportRequest_Software)(nil),
		(*ReportRequest_User)(nil),
		(*ReportRequest_Process)(nil),
		(*ReportRequest_Peripheral)(nil),
	}
	file_internal_proto_teamx_proto_msgTypes[25].OneofWrappers = []any{
		(*FileChunk_TransferRequest)(nil),
		(*FileChunk_TransferResponse)(nil),
		(*FileChunk_FileData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_teamx_proto_rawDesc), len(file_internal_proto_teamx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_teamx_proto_goTypes,
		DependencyIndexes: file_internal_proto_teamx_proto_depIdxs,
		MessageInfos:      file_internal_proto_teamx_proto_msgTypes,
	}.Build()
	File_internal_proto_teamx_proto = out.File
	file_internal_proto_teamx_proto_goTypes = nil
	file_internal_proto_teamx_proto_depIdxs = nil
}
