// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: teamx.proto

package protoconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
	proto "teamx/internal/proto"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TeamXName is the fully-qualified name of the TeamX service.
	TeamXName = "teamx.proto.TeamX"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TeamXRegisterProcedure is the fully-qualified name of the TeamX's Register RPC.
	TeamXRegisterProcedure = "/teamx.proto.TeamX/Register"
	// TeamXChannelProcedure is the fully-qualified name of the TeamX's Channel RPC.
	TeamXChannelProcedure = "/teamx.proto.TeamX/Channel"
	// TeamXTransferFileProcedure is the fully-qualified name of the TeamX's TransferFile RPC.
	TeamXTransferFileProcedure = "/teamx.proto.TeamX/TransferFile"
	// TeamXListTerminalsProcedure is the fully-qualified name of the TeamX's ListTerminals RPC.
	TeamXListTerminalsProcedure = "/teamx.proto.TeamX/ListTerminals"
	// TeamXGetTerminalProcedure is the fully-qualified name of the TeamX's GetTerminal RPC.
	TeamXGetTerminalProcedure = "/teamx.proto.TeamX/GetTerminal"
	// TeamXGetTerminalHistoryProcedure is the fully-qualified name of the TeamX's GetTerminalHistory
	// RPC.
	TeamXGetTerminalHistoryProcedure = "/teamx.proto.TeamX/GetTerminalHistory"
	// TeamXDisconnectTerminalProcedure is the fully-qualified name of the TeamX's DisconnectTerminal
	// RPC.
	TeamXDisconnectTerminalProcedure = "/teamx.proto.TeamX/DisconnectTerminal"
	// TeamXBlockTerminalProcedure is the fully-qualified name of the TeamX's BlockTerminal RPC.
	TeamXBlockTerminalProcedure = "/teamx.proto.TeamX/BlockTerminal"
	// TeamXUnblockTerminalProcedure is the fully-qualified name of the TeamX's UnblockTerminal RPC.
	TeamXUnblockTerminalProcedure = "/teamx.proto.TeamX/UnblockTerminal"
	// TeamXSendCommandProcedure is the fully-qualified name of the TeamX's SendCommand RPC.
	TeamXSendCommandProcedure = "/teamx.proto.TeamX/SendCommand"
	// TeamXGetCommandLogProcedure is the fully-qualified name of the TeamX's GetCommandLog RPC.
	TeamXGetCommandLogProcedure = "/teamx.proto.TeamX/GetCommandLog"
)

// TeamXClient is a client for the teamx.proto.TeamX service.
type TeamXClient interface {
	// Register performs a one-shot handshake: client → server.
	// The server returns a session_id the client must use thereafter.
	Register(context.Context, *connect.Request[proto.HandshakeRequest]) (*connect.Response[proto.HandshakeResponse], error)
	// Channel is the main bidirectional communication pipe.
	// Once registered, the client opens this stream and keeps it alive.
	//
	//	Client → Server : Heartbeat / ReportRequest / CommandResult
	//	Server → Client : HeartbeatAck  / Command
	Channel(context.Context) *connect.BidiStreamForClient[proto.ClientMessage, proto.ServerMessage]
	// TransferFile handles file upload / download with chunked framing.
	// Phase 7 才启用，Phase 0.2 先定义协议。
	TransferFile(context.Context) *connect.BidiStreamForClient[proto.FileChunk, proto.FileChunk]
	ListTerminals(context.Context, *connect.Request[proto.ListTerminalsRequest]) (*connect.Response[proto.ListTerminalsResponse], error)
	GetTerminal(context.Context, *connect.Request[proto.GetTerminalRequest]) (*connect.Response[proto.GetTerminalResponse], error)
	GetTerminalHistory(context.Context, *connect.Request[proto.GetTerminalHistoryRequest]) (*connect.Response[proto.GetTerminalHistoryResponse], error)
	DisconnectTerminal(context.Context, *connect.Request[proto.DisconnectTerminalRequest]) (*connect.Response[proto.DisconnectTerminalResponse], error)
	BlockTerminal(context.Context, *connect.Request[proto.BlockTerminalRequest]) (*connect.Response[proto.BlockTerminalResponse], error)
	UnblockTerminal(context.Context, *connect.Request[proto.UnblockTerminalRequest]) (*connect.Response[proto.UnblockTerminalResponse], error)
	SendCommand(context.Context, *connect.Request[proto.SendCommandRequest]) (*connect.Response[proto.SendCommandResponse], error)
	GetCommandLog(context.Context, *connect.Request[proto.GetCommandLogRequest]) (*connect.Response[proto.GetCommandLogResponse], error)
}

// NewTeamXClient constructs a client for the teamx.proto.TeamX service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTeamXClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TeamXClient {
	baseURL = strings.TrimRight(baseURL, "/")
	teamXMethods := proto.File_teamx_proto.Services().ByName("TeamX").Methods()
	return &teamXClient{
		register: connect.NewClient[proto.HandshakeRequest, proto.HandshakeResponse](
			httpClient,
			baseURL+TeamXRegisterProcedure,
			connect.WithSchema(teamXMethods.ByName("Register")),
			connect.WithClientOptions(opts...),
		),
		channel: connect.NewClient[proto.ClientMessage, proto.ServerMessage](
			httpClient,
			baseURL+TeamXChannelProcedure,
			connect.WithSchema(teamXMethods.ByName("Channel")),
			connect.WithClientOptions(opts...),
		),
		transferFile: connect.NewClient[proto.FileChunk, proto.FileChunk](
			httpClient,
			baseURL+TeamXTransferFileProcedure,
			connect.WithSchema(teamXMethods.ByName("TransferFile")),
			connect.WithClientOptions(opts...),
		),
		listTerminals: connect.NewClient[proto.ListTerminalsRequest, proto.ListTerminalsResponse](
			httpClient,
			baseURL+TeamXListTerminalsProcedure,
			connect.WithSchema(teamXMethods.ByName("ListTerminals")),
			connect.WithClientOptions(opts...),
		),
		getTerminal: connect.NewClient[proto.GetTerminalRequest, proto.GetTerminalResponse](
			httpClient,
			baseURL+TeamXGetTerminalProcedure,
			connect.WithSchema(teamXMethods.ByName("GetTerminal")),
			connect.WithClientOptions(opts...),
		),
		getTerminalHistory: connect.NewClient[proto.GetTerminalHistoryRequest, proto.GetTerminalHistoryResponse](
			httpClient,
			baseURL+TeamXGetTerminalHistoryProcedure,
			connect.WithSchema(teamXMethods.ByName("GetTerminalHistory")),
			connect.WithClientOptions(opts...),
		),
		disconnectTerminal: connect.NewClient[proto.DisconnectTerminalRequest, proto.DisconnectTerminalResponse](
			httpClient,
			baseURL+TeamXDisconnectTerminalProcedure,
			connect.WithSchema(teamXMethods.ByName("DisconnectTerminal")),
			connect.WithClientOptions(opts...),
		),
		blockTerminal: connect.NewClient[proto.BlockTerminalRequest, proto.BlockTerminalResponse](
			httpClient,
			baseURL+TeamXBlockTerminalProcedure,
			connect.WithSchema(teamXMethods.ByName("BlockTerminal")),
			connect.WithClientOptions(opts...),
		),
		unblockTerminal: connect.NewClient[proto.UnblockTerminalRequest, proto.UnblockTerminalResponse](
			httpClient,
			baseURL+TeamXUnblockTerminalProcedure,
			connect.WithSchema(teamXMethods.ByName("UnblockTerminal")),
			connect.WithClientOptions(opts...),
		),
		sendCommand: connect.NewClient[proto.SendCommandRequest, proto.SendCommandResponse](
			httpClient,
			baseURL+TeamXSendCommandProcedure,
			connect.WithSchema(teamXMethods.ByName("SendCommand")),
			connect.WithClientOptions(opts...),
		),
		getCommandLog: connect.NewClient[proto.GetCommandLogRequest, proto.GetCommandLogResponse](
			httpClient,
			baseURL+TeamXGetCommandLogProcedure,
			connect.WithSchema(teamXMethods.ByName("GetCommandLog")),
			connect.WithClientOptions(opts...),
		),
	}
}

// teamXClient implements TeamXClient.
type teamXClient struct {
	register           *connect.Client[proto.HandshakeRequest, proto.HandshakeResponse]
	channel            *connect.Client[proto.ClientMessage, proto.ServerMessage]
	transferFile       *connect.Client[proto.FileChunk, proto.FileChunk]
	listTerminals      *connect.Client[proto.ListTerminalsRequest, proto.ListTerminalsResponse]
	getTerminal        *connect.Client[proto.GetTerminalRequest, proto.GetTerminalResponse]
	getTerminalHistory *connect.Client[proto.GetTerminalHistoryRequest, proto.GetTerminalHistoryResponse]
	disconnectTerminal *connect.Client[proto.DisconnectTerminalRequest, proto.DisconnectTerminalResponse]
	blockTerminal      *connect.Client[proto.BlockTerminalRequest, proto.BlockTerminalResponse]
	unblockTerminal    *connect.Client[proto.UnblockTerminalRequest, proto.UnblockTerminalResponse]
	sendCommand        *connect.Client[proto.SendCommandRequest, proto.SendCommandResponse]
	getCommandLog      *connect.Client[proto.GetCommandLogRequest, proto.GetCommandLogResponse]
}

// Register calls teamx.proto.TeamX.Register.
func (c *teamXClient) Register(ctx context.Context, req *connect.Request[proto.HandshakeRequest]) (*connect.Response[proto.HandshakeResponse], error) {
	return c.register.CallUnary(ctx, req)
}

// Channel calls teamx.proto.TeamX.Channel.
func (c *teamXClient) Channel(ctx context.Context) *connect.BidiStreamForClient[proto.ClientMessage, proto.ServerMessage] {
	return c.channel.CallBidiStream(ctx)
}

// TransferFile calls teamx.proto.TeamX.TransferFile.
func (c *teamXClient) TransferFile(ctx context.Context) *connect.BidiStreamForClient[proto.FileChunk, proto.FileChunk] {
	return c.transferFile.CallBidiStream(ctx)
}

// ListTerminals calls teamx.proto.TeamX.ListTerminals.
func (c *teamXClient) ListTerminals(ctx context.Context, req *connect.Request[proto.ListTerminalsRequest]) (*connect.Response[proto.ListTerminalsResponse], error) {
	return c.listTerminals.CallUnary(ctx, req)
}

// GetTerminal calls teamx.proto.TeamX.GetTerminal.
func (c *teamXClient) GetTerminal(ctx context.Context, req *connect.Request[proto.GetTerminalRequest]) (*connect.Response[proto.GetTerminalResponse], error) {
	return c.getTerminal.CallUnary(ctx, req)
}

// GetTerminalHistory calls teamx.proto.TeamX.GetTerminalHistory.
func (c *teamXClient) GetTerminalHistory(ctx context.Context, req *connect.Request[proto.GetTerminalHistoryRequest]) (*connect.Response[proto.GetTerminalHistoryResponse], error) {
	return c.getTerminalHistory.CallUnary(ctx, req)
}

// DisconnectTerminal calls teamx.proto.TeamX.DisconnectTerminal.
func (c *teamXClient) DisconnectTerminal(ctx context.Context, req *connect.Request[proto.DisconnectTerminalRequest]) (*connect.Response[proto.DisconnectTerminalResponse], error) {
	return c.disconnectTerminal.CallUnary(ctx, req)
}

// BlockTerminal calls teamx.proto.TeamX.BlockTerminal.
func (c *teamXClient) BlockTerminal(ctx context.Context, req *connect.Request[proto.BlockTerminalRequest]) (*connect.Response[proto.BlockTerminalResponse], error) {
	return c.blockTerminal.CallUnary(ctx, req)
}

// UnblockTerminal calls teamx.proto.TeamX.UnblockTerminal.
func (c *teamXClient) UnblockTerminal(ctx context.Context, req *connect.Request[proto.UnblockTerminalRequest]) (*connect.Response[proto.UnblockTerminalResponse], error) {
	return c.unblockTerminal.CallUnary(ctx, req)
}

// SendCommand calls teamx.proto.TeamX.SendCommand.
func (c *teamXClient) SendCommand(ctx context.Context, req *connect.Request[proto.SendCommandRequest]) (*connect.Response[proto.SendCommandResponse], error) {
	return c.sendCommand.CallUnary(ctx, req)
}

// GetCommandLog calls teamx.proto.TeamX.GetCommandLog.
func (c *teamXClient) GetCommandLog(ctx context.Context, req *connect.Request[proto.GetCommandLogRequest]) (*connect.Response[proto.GetCommandLogResponse], error) {
	return c.getCommandLog.CallUnary(ctx, req)
}

// TeamXHandler is an implementation of the teamx.proto.TeamX service.
type TeamXHandler interface {
	// Register performs a one-shot handshake: client → server.
	// The server returns a session_id the client must use thereafter.
	Register(context.Context, *connect.Request[proto.HandshakeRequest]) (*connect.Response[proto.HandshakeResponse], error)
	// Channel is the main bidirectional communication pipe.
	// Once registered, the client opens this stream and keeps it alive.
	//
	//	Client → Server : Heartbeat / ReportRequest / CommandResult
	//	Server → Client : HeartbeatAck  / Command
	Channel(context.Context, *connect.BidiStream[proto.ClientMessage, proto.ServerMessage]) error
	// TransferFile handles file upload / download with chunked framing.
	// Phase 7 才启用，Phase 0.2 先定义协议。
	TransferFile(context.Context, *connect.BidiStream[proto.FileChunk, proto.FileChunk]) error
	ListTerminals(context.Context, *connect.Request[proto.ListTerminalsRequest]) (*connect.Response[proto.ListTerminalsResponse], error)
	GetTerminal(context.Context, *connect.Request[proto.GetTerminalRequest]) (*connect.Response[proto.GetTerminalResponse], error)
	GetTerminalHistory(context.Context, *connect.Request[proto.GetTerminalHistoryRequest]) (*connect.Response[proto.GetTerminalHistoryResponse], error)
	DisconnectTerminal(context.Context, *connect.Request[proto.DisconnectTerminalRequest]) (*connect.Response[proto.DisconnectTerminalResponse], error)
	BlockTerminal(context.Context, *connect.Request[proto.BlockTerminalRequest]) (*connect.Response[proto.BlockTerminalResponse], error)
	UnblockTerminal(context.Context, *connect.Request[proto.UnblockTerminalRequest]) (*connect.Response[proto.UnblockTerminalResponse], error)
	SendCommand(context.Context, *connect.Request[proto.SendCommandRequest]) (*connect.Response[proto.SendCommandResponse], error)
	GetCommandLog(context.Context, *connect.Request[proto.GetCommandLogRequest]) (*connect.Response[proto.GetCommandLogResponse], error)
}

// NewTeamXHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTeamXHandler(svc TeamXHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	teamXMethods := proto.File_teamx_proto.Services().ByName("TeamX").Methods()
	teamXRegisterHandler := connect.NewUnaryHandler(
		TeamXRegisterProcedure,
		svc.Register,
		connect.WithSchema(teamXMethods.ByName("Register")),
		connect.WithHandlerOptions(opts...),
	)
	teamXChannelHandler := connect.NewBidiStreamHandler(
		TeamXChannelProcedure,
		svc.Channel,
		connect.WithSchema(teamXMethods.ByName("Channel")),
		connect.WithHandlerOptions(opts...),
	)
	teamXTransferFileHandler := connect.NewBidiStreamHandler(
		TeamXTransferFileProcedure,
		svc.TransferFile,
		connect.WithSchema(teamXMethods.ByName("TransferFile")),
		connect.WithHandlerOptions(opts...),
	)
	teamXListTerminalsHandler := connect.NewUnaryHandler(
		TeamXListTerminalsProcedure,
		svc.ListTerminals,
		connect.WithSchema(teamXMethods.ByName("ListTerminals")),
		connect.WithHandlerOptions(opts...),
	)
	teamXGetTerminalHandler := connect.NewUnaryHandler(
		TeamXGetTerminalProcedure,
		svc.GetTerminal,
		connect.WithSchema(teamXMethods.ByName("GetTerminal")),
		connect.WithHandlerOptions(opts...),
	)
	teamXGetTerminalHistoryHandler := connect.NewUnaryHandler(
		TeamXGetTerminalHistoryProcedure,
		svc.GetTerminalHistory,
		connect.WithSchema(teamXMethods.ByName("GetTerminalHistory")),
		connect.WithHandlerOptions(opts...),
	)
	teamXDisconnectTerminalHandler := connect.NewUnaryHandler(
		TeamXDisconnectTerminalProcedure,
		svc.DisconnectTerminal,
		connect.WithSchema(teamXMethods.ByName("DisconnectTerminal")),
		connect.WithHandlerOptions(opts...),
	)
	teamXBlockTerminalHandler := connect.NewUnaryHandler(
		TeamXBlockTerminalProcedure,
		svc.BlockTerminal,
		connect.WithSchema(teamXMethods.ByName("BlockTerminal")),
		connect.WithHandlerOptions(opts...),
	)
	teamXUnblockTerminalHandler := connect.NewUnaryHandler(
		TeamXUnblockTerminalProcedure,
		svc.UnblockTerminal,
		connect.WithSchema(teamXMethods.ByName("UnblockTerminal")),
		connect.WithHandlerOptions(opts...),
	)
	teamXSendCommandHandler := connect.NewUnaryHandler(
		TeamXSendCommandProcedure,
		svc.SendCommand,
		connect.WithSchema(teamXMethods.ByName("SendCommand")),
		connect.WithHandlerOptions(opts...),
	)
	teamXGetCommandLogHandler := connect.NewUnaryHandler(
		TeamXGetCommandLogProcedure,
		svc.GetCommandLog,
		connect.WithSchema(teamXMethods.ByName("GetCommandLog")),
		connect.WithHandlerOptions(opts...),
	)
	return "/teamx.proto.TeamX/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TeamXRegisterProcedure:
			teamXRegisterHandler.ServeHTTP(w, r)
		case TeamXChannelProcedure:
			teamXChannelHandler.ServeHTTP(w, r)
		case TeamXTransferFileProcedure:
			teamXTransferFileHandler.ServeHTTP(w, r)
		case TeamXListTerminalsProcedure:
			teamXListTerminalsHandler.ServeHTTP(w, r)
		case TeamXGetTerminalProcedure:
			teamXGetTerminalHandler.ServeHTTP(w, r)
		case TeamXGetTerminalHistoryProcedure:
			teamXGetTerminalHistoryHandler.ServeHTTP(w, r)
		case TeamXDisconnectTerminalProcedure:
			teamXDisconnectTerminalHandler.ServeHTTP(w, r)
		case TeamXBlockTerminalProcedure:
			teamXBlockTerminalHandler.ServeHTTP(w, r)
		case TeamXUnblockTerminalProcedure:
			teamXUnblockTerminalHandler.ServeHTTP(w, r)
		case TeamXSendCommandProcedure:
			teamXSendCommandHandler.ServeHTTP(w, r)
		case TeamXGetCommandLogProcedure:
			teamXGetCommandLogHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTeamXHandler returns CodeUnimplemented from all methods.
type UnimplementedTeamXHandler struct{}

func (UnimplementedTeamXHandler) Register(context.Context, *connect.Request[proto.HandshakeRequest]) (*connect.Response[proto.HandshakeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("teamx.proto.TeamX.Register is not implemented"))
}

func (UnimplementedTeamXHandler) Channel(context.Context, *connect.BidiStream[proto.ClientMessage, proto.ServerMessage]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("teamx.proto.TeamX.Channel is not implemented"))
}

func (UnimplementedTeamXHandler) TransferFile(context.Context, *connect.BidiStream[proto.FileChunk, proto.FileChunk]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("teamx.proto.TeamX.TransferFile is not implemented"))
}

func (UnimplementedTeamXHandler) ListTerminals(context.Context, *connect.Request[proto.ListTerminalsRequest]) (*connect.Response[proto.ListTerminalsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("teamx.proto.TeamX.ListTerminals is not implemented"))
}

func (UnimplementedTeamXHandler) GetTerminal(context.Context, *connect.Request[proto.GetTerminalRequest]) (*connect.Response[proto.GetTerminalResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("teamx.proto.TeamX.GetTerminal is not implemented"))
}

func (UnimplementedTeamXHandler) GetTerminalHistory(context.Context, *connect.Request[proto.GetTerminalHistoryRequest]) (*connect.Response[proto.GetTerminalHistoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("teamx.proto.TeamX.GetTerminalHistory is not implemented"))
}

func (UnimplementedTeamXHandler) DisconnectTerminal(context.Context, *connect.Request[proto.DisconnectTerminalRequest]) (*connect.Response[proto.DisconnectTerminalResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("teamx.proto.TeamX.DisconnectTerminal is not implemented"))
}

func (UnimplementedTeamXHandler) BlockTerminal(context.Context, *connect.Request[proto.BlockTerminalRequest]) (*connect.Response[proto.BlockTerminalResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("teamx.proto.TeamX.BlockTerminal is not implemented"))
}

func (UnimplementedTeamXHandler) UnblockTerminal(context.Context, *connect.Request[proto.UnblockTerminalRequest]) (*connect.Response[proto.UnblockTerminalResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("teamx.proto.TeamX.UnblockTerminal is not implemented"))
}

func (UnimplementedTeamXHandler) SendCommand(context.Context, *connect.Request[proto.SendCommandRequest]) (*connect.Response[proto.SendCommandResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("teamx.proto.TeamX.SendCommand is not implemented"))
}

func (UnimplementedTeamXHandler) GetCommandLog(context.Context, *connect.Request[proto.GetCommandLogRequest]) (*connect.Response[proto.GetCommandLogResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("teamx.proto.TeamX.GetCommandLog is not implemented"))
}
